# .gitpod.yml
image: gitpod/workspace-python-3.10

ports:
  - port: 8888
    onOpen: ignore
    visibility: public

tasks:
  - name: Setup & register kernel
    init: |
      ./setup_env.sh
    command: |
      # Once setup is done, just open the notebook
      code notebook.ipynb

# Configure VS Code
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
