# GitPod Configuration
tasks:
  - init: pip install -r requirements.txt
    command: |
      python -m http.server 9000 &
      gp open count_tags.py
      sleep 2
      gp preview $(gp url 9000)/data/SUMMARY.md

ports:
  - port: 9000
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-python.python 