# GitPod Configuration
image: gitpod/workspace-python-3.10

ports:
  - port: 8888
    onOpen: open-browser
    visibility: public

tasks:
  - name: Install dependencies and start Jupyter
    init: |
      # Install Python dependencies
      pip install -r requirements.txt
    command: |
      # Start Jupyter Notebook with runner.ipynb as the default file
      jupyter notebook --ip=0.0.0.0 --NotebookApp.token='' --NotebookApp.password='' runner.ipynb

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter 