# .gitpod.yml
image: gitpod/workspace-python-3.10

ports:
  - port: 8888          # your main Jupyter server
    onOpen: ignore
  - port: 9000
    onOpen: ignore
  - port: 9001
    onOpen: ignore
  - port: 9002
    onOpen: ignore

tasks:
  - name: Setup & register kernel
    init: |
      ./setup_env.sh
    command: |
      # Once setup is done, just open the notebook
      code notebook.ipynb

# Configure VS Code
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - donjayamanne.vscode-default-python-kernel

